language: node_js

matrix:
  include:
    - node_js: "8"
      addons:
        postgresql: "9.6"
    - node_js: "9"
      addons:
        postgresql: "9.6"
    - node_js: "10"
      addons:
        postgresql: "9.6"
